- name: Alpha Provisions 
  hosts: alpha 
  become: True
  tasks:
      - apt: name=tree state=latest
      - get_url: url=https://github.com/docker/machine/releases/download/v0.8.0/docker-machine-Linux-x86_64 dest=/usr/local/bin/docker-machine mode=0555
      - command: docker-machine --version
